<a href="https://colab.research.google.com/github/volodymyr-holovan/DTA2026/blob/main/homework/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [1]:
import numpy as np

temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print(temps)
print(f"Кількість вимірів: {temps.ndim}")
print(f"Форма: {temps.shape}")
print(f"Кількість елементів: {temps.size}")
print(f"Тип даних: {temps.dtype}")
print(f"Мінімальна температура: {temps.min()} °C")
print(f"Максимальна температура: {temps.max()} °C")
print(f"Середньорічна температура: {temps.mean():.1f} °C")

[-5 -4  2 10 17 21 23 22 16  9  2 -3]
Кількість вимірів: 1
Форма: (12,)
Кількість елементів: 12
Тип даних: int64
Мінімальна температура: -5 °C
Максимальна температура: 23 °C
Середньорічна температура: 9.2 °C


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [2]:
plan = np.full((3, 4), 50)
bonus = np.zeros((3, 4), dtype=int)
total_plan = plan + bonus

print(plan)
print(f"Форма: {plan.shape}")
print(f"Кількість елементів: {plan.size}")
print(bonus)
print(total_plan)
print(np.array_equal(total_plan, plan))

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
Форма: (3, 4)
Кількість елементів: 12
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
True


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [3]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

print(sales[:7])
print(sales[7:])
print(sales[[5, 6, 12, 13]])
print(sales[::2])
print(sales[::-1])

[320 415 290 480 350 620 580]
[310 440 305 510 370 650 595]
[620 580 650 595]
[320 290 350 580 440 510 650]
[595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [4]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

print(grades[0])
print(grades[:, 2])
print(grades[1:3, 1:4])
print(grades[-1, -1])

[85 72 91 78 88]
[91 74 82 68]
[[88 74 95]
 [65 82 70]]
79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [5]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

prices_uah = np.round(prices_usd * 41.5, 2)
prices_with_vat = np.round(prices_uah * 1.2, 2)

print(f"Ціни у гривнях: {prices_uah}")
print(f"Ціни з ПДВ: {prices_with_vat}")
print(f"Мінімальна ціна з ПДВ: {prices_with_vat.min():.2f} грн")
print(f"Максимальна ціна з ПДВ: {prices_with_vat.max():.2f} грн")
print(f"Середня ціна з ПДВ: {prices_with_vat.mean():.2f} грн")
print(f"Загальна вартість кошика: {prices_with_vat.sum():.2f} грн")

Ціни у гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Мінімальна ціна з ПДВ: 398.40 грн
Максимальна ціна з ПДВ: 6225.00 грн
Середня ціна з ПДВ: 2151.57 грн
Загальна вартість кошика: 15061.00 грн


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [6]:
quantity = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names = np.array(['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
                  'Мишка', 'Ручка', 'Навушники'])

item_values = quantity * cost_each
max_index = np.argmax(item_values)
min_index = np.argmin(item_values)

print(f"Вартість кожного товару: {item_values}")
print(f"Загальна вартість складу: {item_values.sum()} грн")
print(f"Найбільша сумарна вартість: {names[max_index]} — {item_values[max_index]} грн")
print(f"Найменша сумарна вартість: {names[min_index]} — {item_values[min_index]} грн")
print(f"Середня вартість одного найменування: {item_values.mean():.2f} грн")

Вартість кожного товару: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість складу: 393000 грн
Найбільша сумарна вартість: Монітор — 171000 грн
Найменша сумарна вартість: Зошит — 13500 грн
Середня вартість одного найменування: 56142.86 грн


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [7]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                          31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

on_time = delivery_time[delivery_time <= 30]
late = delivery_time[delivery_time > 30]

print(f"Вчасно: {on_time}")
print(f"Запізнілі: {late}")
print(f"Кількість вчасних: {on_time.size}")
print(f"Кількість запізнілих: {late.size}")
print(f"Відсоток запізнілих: {late.size / delivery_time.size * 100:.1f}%")
print(f"Середня затримка: {(late - 30).mean():.1f} хв")

Вчасно: [22 28 19 27 24 26 18 29 23 20]
Запізнілі: [35 41 55 33 48 31 52 38 44 36]
Кількість вчасних: 10
Кількість запізнілих: 10
Відсоток запізнілих: 50.0%
Середня затримка: 11.3 хв


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [8]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

average_sales = daily.mean()
above_average_indices = np.where(daily > average_sales)[0]
status = np.where(daily > average_sales, 'Гарний день', 'Звичайний день')

print(f"Середні продажі: {average_sales:.2f}")
print(f"Дні з продажами вище середнього: {above_average_indices + 1}")
print(f"Кількість таких днів: {above_average_indices.size}")
print(np.column_stack((daily[:10], status[:10])))

Середні продажі: 434.23
Дні з продажами вище середнього: [ 2  6  8 10 13 15 17 19 21 22 23 24 25 29]
Кількість таких днів: 14
[['202' 'Звичайний день']
 ['535' 'Гарний день']
 ['370' 'Звичайний день']
 ['206' 'Звичайний день']
 ['171' 'Звичайний день']
 ['800' 'Гарний день']
 ['120' 'Звичайний день']
 ['714' 'Гарний день']
 ['221' 'Звичайний день']
 ['566' 'Гарний день']]


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [9]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

hourly_matrix = hourly.reshape(6, 4)
block_sums = hourly_matrix.sum(axis=1)
sorted_hourly = np.sort(hourly)
sorted_indices = np.argsort(hourly)
top_three = sorted_indices[-3:][::-1]

print(hourly_matrix)
print(f"Суми за блоками: {block_sums}")
print(f"Відсортований масив: {sorted_hourly}")
print(f"Індекси за зростанням: {sorted_indices}")
print(f"Топ-3 години: {top_three}")

[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Суми за блоками: [ 28  66 235 240 257 112]
Відсортований масив: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Індекси за зростанням: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
Топ-3 години: [18 12 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [10]:
np.random.seed(99)
ages = np.random.randint(18, 66, size=50)
scores = np.round(np.random.normal(7, 1.5, size=50), 1)
scores = np.clip(scores, 1, 10)
satisfied_count = (scores >= 8).sum()

print(f"Середній вік: {ages.mean():.2f}")
print(f"Середня оцінка задоволеності: {scores.mean():.2f}")
print(f"Кількість задоволених клієнтів: {satisfied_count}")
print(f"Відсоток задоволених: {satisfied_count / scores.size * 100:.1f}%")

Середній вік: 41.80
Середня оцінка задоволеності: 6.87
Кількість задоволених клієнтів: 10
Відсоток задоволених: 20.0%


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [11]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [12]:
total_revenue = sales_56.sum()
average_daily = sales_56.mean()

print(f"Загальна виручка: {total_revenue} грн")
print(f"Середньоденна виручка: {average_daily:.2f} грн")
print(f"Мінімальний денний продаж: {sales_56.min()} грн")
print(f"Максимальний денний продаж: {sales_56.max()} грн")
print(f"Стандартне відхилення: {sales_56.std():.2f} грн")

Загальна виручка: 31819 грн
Середньоденна виручка: 568.20 грн
Мінімальний денний продаж: 222 грн
Максимальний денний продаж: 1072 грн
Стандартне відхилення: 195.52 грн


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [13]:
weekly_sales = sales_56.reshape(8, 7)
weekly_revenue = weekly_sales.sum(axis=1)
best_week_index = np.argmax(weekly_revenue)
weekday_average = weekly_sales.mean(axis=0)
best_weekday = np.argmax(weekday_average)

print(weekly_sales)
print(f"Виручка за тижнями: {weekly_revenue}")
print(f"Найкращий тиждень: {best_week_index + 1}, сума: {weekly_revenue[best_week_index]} грн")
print(f"Середньоденна виручка за днями тижня: {np.round(weekday_average, 2)}")
print(f"Найприбутковіший день тижня: {best_weekday}")

[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]
Виручка за тижнями: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: 5, сума: 5036 грн
Середньоденна виручка за днями тижня: [520.38 455.5  565.88 607.75 463.75 629.75 734.38]
Найприбутковіший день тижня: 6


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [14]:
weak_mask = sales_56 < 400
strong_mask = sales_56 > 700
weak_sales = sales_56[weak_mask]
strong_sales = sales_56[strong_mask]
labels = np.where(weak_mask, 'Слабкий', np.where(strong_mask, 'Сильний', 'Нормальний'))

print(f"Кількість слабких днів: {weak_sales.size}")
print(f"Кількість сильних днів: {strong_sales.size}")
print(f"Середня виручка у слабкі дні: {weak_sales.mean():.2f} грн")
print(f"Середня виручка у сильні дні: {strong_sales.mean():.2f} грн")
print(np.column_stack((sales_56[:14], labels[:14])))

Кількість слабких днів: 12
Кількість сильних днів: 19
Середня виручка у слабкі дні: 302.00 грн
Середня виручка у сильні дні: 785.16 грн
[['706' 'Сильний']
 ['739' 'Сильний']
 ['748' 'Сильний']
 ['646' 'Нормальний']
 ['383' 'Слабкий']
 ['556' 'Нормальний']
 ['777' 'Сильний']
 ['427' 'Нормальний']
 ['274' 'Слабкий']
 ['522' 'Нормальний']
 ['680' 'Нормальний']
 ['708' 'Сильний']
 ['465' 'Нормальний']
 ['845' 'Сильний']]


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ✅ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ✅ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ✅ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ✅ |
| 5 — reshape та сортування | 5.1 | 1 | ✅ |
| 6 — Генерація випадкових | 6.1 | 1 | ✅ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ✅ |
| **Разом** | | **13** | |
