<a href="https://colab.research.google.com/github/volodymyr-holovan/DTA2026/blob/main/homework/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [1]:
import numpy as np

# Твій код:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print(temps)
print("ndim:", temps.ndim)
print("shape:", temps.shape)
print("size:", temps.size)
print("dtype:", temps.dtype)

[-5 -4  2 10 17 21 23 22 16  9  2 -3]
ndim: 1
shape: (12,)
size: 12
dtype: int64


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [2]:
# Твій код:
plan = np.full((3, 4), 50)
print(plan)
print("shape:", plan.shape)
print("elements:", plan.size)

bonus = np.array([10, 15, 20, 25])
total = plan + bonus
print(total)

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
shape: (3, 4)
elements: 12
[[60 65 70 75]
 [60 65 70 75]
 [60 65 70 75]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [3]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("Перший тиждень:", sales[:7])
print("Другий тиждень:", sales[7:])
print("Парні дні:", sales[::2])
print("Продажі кожного третього дня:", sales[2::3])

Перший тиждень: [320 415 290 480 350 620 580]
Другий тиждень: [310 440 305 510 370 650 595]
Парні дні: [320 290 350 580 440 510 650]
Продажі кожного третього дня: [290 620 440 370]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [4]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
print("Олена:", grades[0])
print("Оцінки з третього предмета:", grades[:, 2])
print("Оцінки вище 80:", grades[grades > 80])
print("Середній бал студентів:", grades.mean(axis=1))

Олена: [85 72 91 78 88]
Оцінки з третього предмета: [91 74 82 68]
Оцінки вище 80: [85 91 88 88 95 90 82 94 85]
Середній бал студентів: [82.8 78.  80.2 77.4]


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [5]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
prices_uah = np.round(prices_usd * 41.5, 2)
prices_with_vat = np.round(prices_uah * 1.2, 2)

print("Ціни в гривнях:", prices_uah)
print("Ціни з ПДВ:", prices_with_vat)
print("Середня ціна:", np.round(prices_with_vat.mean(), 2))

Ціни в гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Середня ціна: 2151.57


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [6]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
total_value = quantity * cost_each
max_index = np.argmax(total_value)

print("Вартість запасів:", total_value)
print("Загальна вартість складу:", total_value.sum())
print("Найдорожчий товар:", names[max_index], total_value[max_index])

Вартість запасів: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість складу: 393000
Найдорожчий товар: Монітор 171000


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [7]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
on_time = delivery_time[delivery_time <= 30]
late = delivery_time[delivery_time > 30]

print("Вчасні замовлення:", on_time)
print("Запізнення:", late)
print("Кількість вчасних:", len(on_time))
print("Кількість запізнень:", len(late))

Вчасні замовлення: [22 28 19 27 24 26 18 29 23 20]
Запізнення: [35 41 55 33 48 31 52 38 44 36]
Кількість вчасних: 10
Кількість запізнень: 10


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [8]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
average = daily.mean()
above_average = daily[daily > average]
count = np.sum(daily > average)

status = np.where(daily > average, "Вище середнього", "Нижче середнього")

print("Середні продажі:", average)
print("Дні вище середнього:", above_average)
print("Кількість таких днів:", count)
print(status)

Середні продажі: 434.23333333333335
Дні вище середнього: [535 800 714 566 558 472 763 761 869 443 591 513 485 559]
Кількість таких днів: 14
['Нижче середнього' 'Вище середнього' 'Нижче середнього'
 'Нижче середнього' 'Нижче середнього' 'Вище середнього'
 'Нижче середнього' 'Вище середнього' 'Нижче середнього' 'Вище середнього'
 'Нижче середнього' 'Нижче середнього' 'Вище середнього'
 'Нижче середнього' 'Вище середнього' 'Нижче середнього' 'Вище середнього'
 'Нижче середнього' 'Вище середнього' 'Нижче середнього' 'Вище середнього'
 'Вище середнього' 'Вище середнього' 'Вище середнього' 'Вище середнього'
 'Нижче середнього' 'Нижче середнього' 'Нижче середнього'
 'Вище середнього' 'Нижче середнього']


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [9]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
hourly_matrix = hourly.reshape(6, 4)
print(hourly_matrix)

print("Максимум:", hourly_matrix.max())
print("Мінімум:", hourly_matrix.min())

sorted_values = np.sort(hourly)
indexes = np.argsort(hourly)

print("Відсортовані значення:", sorted_values)
print("Індекси:", indexes)

[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Максимум: 74
Мінімум: 3
Відсортовані значення: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Індекси: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [10]:
# Твій код:
np.random.seed(99)

ages = np.random.randint(18, 66, 50)
scores = np.round(np.random.normal(7, 1.5, 50), 1)
scores = np.clip(scores, 1, 10)
answers = np.random.choice(["Так", "Ні"], 50)

print("Вік:", ages)
print("Оцінки:", scores)
print("Відповіді:", answers)
print("Середній вік:", ages.mean())
print("Середня оцінка:", scores.mean())

Вік: [19 53 58 27 58 36 22 23 19 41 53 19 47 56 61 41 20 18 30 58 26 38 57 33
 65 45 55 64 54 62 35 27 50 39 65 59 53 37 40 44 23 30 50 45 19 62 29 29
 47 49]
Оцінки: [ 5.7  6.4  5.7  9.2  5.5  6.1  6.8  7.9  4.8  8.8  7.5  6.4  7.2  6.2
  6.7  7.4  6.   4.7  7.1  5.   5.4  5.6  8.   8.5  9.1  9.6  7.1  7.1
  7.4  7.8  6.7  7.1  7.3  5.5  6.7  5.5  7.9  8.3  4.9  6.2 10.   4.8
  7.6  4.7  6.5  4.2  7.7  7.7  9.4  8. ]
Відповіді: ['Так' 'Так' 'Так' 'Так' 'Ні' 'Ні' 'Так' 'Так' 'Так' 'Ні' 'Ні' 'Ні' 'Ні'
 'Ні' 'Так' 'Так' 'Так' 'Ні' 'Так' 'Так' 'Ні' 'Ні' 'Так' 'Ні' 'Ні' 'Ні'
 'Ні' 'Ні' 'Так' 'Ні' 'Ні' 'Так' 'Так' 'Ні' 'Так' 'Так' 'Так' 'Ні' 'Так'
 'Так' 'Так' 'Ні' 'Так' 'Так' 'Ні' 'Ні' 'Ні' 'Так' 'Ні' 'Ні']
Середній вік: 41.8
Середня оцінка: 6.867999999999999


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [11]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [12]:
# Твій код:
print("Загальна виручка:", sales_56.sum())
print("Середньоденна виручка:", round(sales_56.mean(), 2))
print("Мінімальний продаж:", sales_56.min())
print("Максимальний продаж:", sales_56.max())
print("Стандартне відхилення:", round(sales_56.std(), 2))

Загальна виручка: 31819
Середньоденна виручка: 568.2
Мінімальний продаж: 222
Максимальний продаж: 1072
Стандартне відхилення: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [13]:
# Твій код:
weekly_sales = sales_56.reshape(8, 7)

week_revenue = weekly_sales.sum(axis=1)
best_week = np.argmax(week_revenue) + 1

daily_average = weekly_sales.mean(axis=0)

print("Матриця 8x7:")
print(weekly_sales)
print("Виручка по тижнях:", week_revenue)
print("Найкращий тиждень:", best_week, "сума:", week_revenue[best_week-1])
print("Середня виручка по днях тижня:", daily_average)

Матриця 8x7:
[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]
Виручка по тижнях: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: 5 сума: 5036
Середня виручка по днях тижня: [520.375 455.5   565.875 607.75  463.75  629.75  734.375]


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [14]:
# Твій код:
weak = sales_56[sales_56 < 400]
strong = sales_56[sales_56 > 700]

labels = np.where(sales_56 < 400, "Слабкий",
         np.where(sales_56 > 700, "Сильний", "Середній"))

print("Кількість слабких днів:", len(weak))
print("Кількість сильних днів:", len(strong))
print("Середня виручка слабких:", weak.mean())
print("Середня виручка сильних:", strong.mean())
print(labels)

Кількість слабких днів: 12
Кількість сильних днів: 19
Середня виручка слабких: 302.0
Середня виручка сильних: 785.1578947368421
['Сильний' 'Сильний' 'Сильний' 'Середній' 'Слабкий' 'Середній' 'Сильний'
 'Середній' 'Слабкий' 'Середній' 'Середній' 'Сильний' 'Середній' 'Сильний'
 'Середній' 'Середній' 'Середній' 'Середній' 'Сильний' 'Середній'
 'Середній' 'Слабкий' 'Слабкий' 'Слабкий' 'Сильний' 'Слабкий' 'Середній'
 'Сильний' 'Сильний' 'Середній' 'Сильний' 'Сильний' 'Середній' 'Сильний'
 'Сильний' 'Слабкий' 'Слабкий' 'Середній' 'Середній' 'Слабкий' 'Сильний'
 'Середній' 'Середній' 'Середній' 'Сильний' 'Середній' 'Слабкий' 'Сильний'
 'Сильний' 'Середній' 'Середній' 'Слабкий' 'Слабкий' 'Середній' 'Сильний'
 'Середній']


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
